// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package webauthn

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Authenticator) DecodeMsg(dc *msgp.Reader) (err error) {
	_ = "STUB: not implemented"
	return nil
}

/* 4 bits */

// Clear omitted fields.

// EncodeMsg implements msgp.Encodable
func (z *Authenticator) EncodeMsg(en *msgp.Writer) (err error) {
	_ = "STUB: not implemented"
	// check for omitted fields
	return nil
}

/* 4 bits */

// variable map header, size zb0001Len

// skip if no fields are to be emitted

// if not omitted
// write "aaguid"

// if not omitted
// write "sc"

// if not omitted
// write "cw"

// if not omitted
// write "aa"

// MarshalMsg implements msgp.Marshaler
func (z *Authenticator) MarshalMsg(b []byte) (o []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil

	// check for omitted fields
}

/* 4 bits */

// variable map header, size zb0001Len

// skip if no fields are to be emitted

// if not omitted
// string "aaguid"

// if not omitted
// string "sc"

// if not omitted
// string "cw"

// if not omitted
// string "aa"

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Authenticator) UnmarshalMsg(bts []byte) (o []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

/* 4 bits */

// Clear omitted fields.

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Authenticator) Msgsize() (s int) { _ = "STUB: not implemented"; return 0 }
