// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package webauthn

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Credential) DecodeMsg(dc *msgp.Reader) (err error) { _ = "STUB: not implemented"; return nil }

/* 3 bits */

// Clear omitted fields.

// EncodeMsg implements msgp.Encodable
func (z *Credential) EncodeMsg(en *msgp.Writer) (err error) {
	_ = "STUB: not implemented"
	// check for omitted fields
	return nil
}

/* 8 bits */

// variable map header, size zb0001Len

// skip if no fields are to be emitted

// write "id"

// write "pk"

// if not omitted
// write "atttype"

// if not omitted
// write "attfmt"

// if not omitted
// write "t"

// write "flg"

// write "a"

// write "att"

// MarshalMsg implements msgp.Marshaler
func (z *Credential) MarshalMsg(b []byte) (o []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil

	// check for omitted fields
}

/* 8 bits */

// variable map header, size zb0001Len

// skip if no fields are to be emitted

// string "id"

// string "pk"

// if not omitted
// string "atttype"

// if not omitted
// string "attfmt"

// if not omitted
// string "t"

// string "flg"

// string "a"

// string "att"

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Credential) UnmarshalMsg(bts []byte) (o []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

/* 3 bits */

// Clear omitted fields.

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Credential) Msgsize() (s int) { _ = "STUB: not implemented"; return 0 }

// DecodeMsg implements msgp.Decodable
func (z *CredentialAttestation) DecodeMsg(dc *msgp.Reader) (err error) {
	_ = "STUB: not implemented"
	return nil
}

/* 5 bits */

// Clear omitted fields.

// EncodeMsg implements msgp.Encodable
func (z *CredentialAttestation) EncodeMsg(en *msgp.Writer) (err error) {
	_ = "STUB: not implemented"
	// check for omitted fields
	return nil
}

/* 5 bits */

// variable map header, size zb0001Len

// skip if no fields are to be emitted

// if not omitted
// write "cdj"

// if not omitted
// write "cdh"

// if not omitted
// write "data"

// if not omitted
// write "alg"

// if not omitted
// write "obj"

// MarshalMsg implements msgp.Marshaler
func (z *CredentialAttestation) MarshalMsg(b []byte) (o []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil

	// check for omitted fields
}

/* 5 bits */

// variable map header, size zb0001Len

// skip if no fields are to be emitted

// if not omitted
// string "cdj"

// if not omitted
// string "cdh"

// if not omitted
// string "data"

// if not omitted
// string "alg"

// if not omitted
// string "obj"

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CredentialAttestation) UnmarshalMsg(bts []byte) (o []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

/* 5 bits */

// Clear omitted fields.

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *CredentialAttestation) Msgsize() (s int) { _ = "STUB: not implemented"; return 0 }

// DecodeMsg implements msgp.Decodable
func (z *CredentialFlags) DecodeMsg(dc *msgp.Reader) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// EncodeMsg implements msgp.Encodable
func (z CredentialFlags) EncodeMsg(en *msgp.Writer) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// MarshalMsg implements msgp.Marshaler
func (z CredentialFlags) MarshalMsg(b []byte) (o []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CredentialFlags) UnmarshalMsg(bts []byte) (o []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z CredentialFlags) Msgsize() (s int) { _ = "STUB: not implemented"; return 0 }

// DecodeMsg implements msgp.Decodable
func (z *Credentials) DecodeMsg(dc *msgp.Reader) (err error) { _ = "STUB: not implemented"; return nil }

// EncodeMsg implements msgp.Encodable
func (z Credentials) EncodeMsg(en *msgp.Writer) (err error) { _ = "STUB: not implemented"; return nil }

// MarshalMsg implements msgp.Marshaler
func (z Credentials) MarshalMsg(b []byte) (o []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *Credentials) UnmarshalMsg(bts []byte) (o []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Credentials) Msgsize() (s int) { _ = "STUB: not implemented"; return 0 }
