// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package webauthn

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *SessionData) DecodeMsg(dc *msgp.Reader) (err error) { _ = "STUB: not implemented"; return nil }

/* 7 bits */

// Clear omitted fields.

// EncodeMsg implements msgp.Encodable
func (z *SessionData) EncodeMsg(en *msgp.Writer) (err error) {
	_ = "STUB: not implemented"
	// check for omitted fields
	return nil
}

/* 9 bits */

// variable map header, size zb0001Len

// skip if no fields are to be emitted

// write "c"

// if not omitted
// write "r"

// if not omitted
// write "u"

// if not omitted
// write "allow"

// write "exp"

// if not omitted
// write "uv"

// if not omitted
// write "exts"

// if not omitted
// write "params"

// if not omitted
// write "cmr"

// MarshalMsg implements msgp.Marshaler
func (z *SessionData) MarshalMsg(b []byte) (o []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil

	// check for omitted fields
}

/* 9 bits */

// variable map header, size zb0001Len

// skip if no fields are to be emitted

// string "c"

// if not omitted
// string "r"

// if not omitted
// string "u"

// if not omitted
// string "allow"

// string "exp"

// if not omitted
// string "uv"

// if not omitted
// string "exts"

// if not omitted
// string "params"

// if not omitted
// string "cmr"

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SessionData) UnmarshalMsg(bts []byte) (o []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

/* 7 bits */

// Clear omitted fields.

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SessionData) Msgsize() (s int) { _ = "STUB: not implemented"; return 0 }
