// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package protocol

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *CredentialParameter) DecodeMsg(dc *msgp.Reader) (err error) {
	_ = "STUB: not implemented"
	return nil
}

/* 2 bits */

// Clear omitted fields.

// EncodeMsg implements msgp.Encodable
func (z CredentialParameter) EncodeMsg(en *msgp.Writer) (err error) {
	_ = "STUB: not implemented"
	// check for omitted fields
	return nil
}

/* 2 bits */

// variable map header, size zb0001Len

// skip if no fields are to be emitted

// if not omitted
// write "typ"

// if not omitted
// write "alg"

// MarshalMsg implements msgp.Marshaler
func (z CredentialParameter) MarshalMsg(b []byte) (o []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil

	// check for omitted fields
}

/* 2 bits */

// variable map header, size zb0001Len

// skip if no fields are to be emitted

// if not omitted
// string "typ"

// if not omitted
// string "alg"

// UnmarshalMsg implements msgp.Unmarshaler
func (z *CredentialParameter) UnmarshalMsg(bts []byte) (o []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

/* 2 bits */

// Clear omitted fields.

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z CredentialParameter) Msgsize() (s int) { _ = "STUB: not implemented"; return 0 }
