// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-webauthn/webauthn/metadata (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -package mocks -destination metadata.go -mock_names Provider=MockMetadataProvider github.com/go-webauthn/webauthn/metadata Provider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"

	metadata "github.com/go-webauthn/webauthn/metadata"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockMetadataProvider is a mock of Provider interface.
type MockMetadataProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataProviderMockRecorder
	isgomock struct{}
}

// MockMetadataProviderMockRecorder is the mock recorder for MockMetadataProvider.
type MockMetadataProviderMockRecorder struct {
	mock *MockMetadataProvider
}

// NewMockMetadataProvider creates a new mock instance.
func NewMockMetadataProvider(ctrl *gomock.Controller) *MockMetadataProvider {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataProvider) EXPECT() *MockMetadataProviderMockRecorder {
	_ = "STUB: not implemented"

	// GetEntry mocks base method.
	return nil
}

func (m *MockMetadataProvider) GetEntry(ctx context.Context, aaguid uuid.UUID) (*metadata.Entry, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEntry indicates an expected call of GetEntry.
func (mr *MockMetadataProviderMockRecorder) GetEntry(ctx, aaguid any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetValidateAttestationTypes mocks base method.
func (m *MockMetadataProvider) GetValidateAttestationTypes(ctx context.Context) bool {
	_ = "STUB: not implemented"
	return false
}

// GetValidateAttestationTypes indicates an expected call of GetValidateAttestationTypes.
func (mr *MockMetadataProviderMockRecorder) GetValidateAttestationTypes(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetValidateEntry mocks base method.
func (m *MockMetadataProvider) GetValidateEntry(ctx context.Context) bool {
	_ = "STUB: not implemented"
	return false
}

// GetValidateEntry indicates an expected call of GetValidateEntry.
func (mr *MockMetadataProviderMockRecorder) GetValidateEntry(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetValidateEntryPermitZeroAAGUID mocks base method.
func (m *MockMetadataProvider) GetValidateEntryPermitZeroAAGUID(ctx context.Context) bool {
	_ = "STUB: not implemented"
	return false
}

// GetValidateEntryPermitZeroAAGUID indicates an expected call of GetValidateEntryPermitZeroAAGUID.
func (mr *MockMetadataProviderMockRecorder) GetValidateEntryPermitZeroAAGUID(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetValidateStatus mocks base method.
func (m *MockMetadataProvider) GetValidateStatus(ctx context.Context) bool {
	_ = "STUB: not implemented"
	return false
}

// GetValidateStatus indicates an expected call of GetValidateStatus.
func (mr *MockMetadataProviderMockRecorder) GetValidateStatus(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetValidateTrustAnchor mocks base method.
func (m *MockMetadataProvider) GetValidateTrustAnchor(ctx context.Context) bool {
	_ = "STUB: not implemented"
	return false
}

// GetValidateTrustAnchor indicates an expected call of GetValidateTrustAnchor.
func (mr *MockMetadataProviderMockRecorder) GetValidateTrustAnchor(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ValidateStatusReports mocks base method.
func (m *MockMetadataProvider) ValidateStatusReports(ctx context.Context, reports []metadata.StatusReport) error {
	_ = "STUB: not implemented"
	return nil
}

// ValidateStatusReports indicates an expected call of ValidateStatusReports.
func (mr *MockMetadataProviderMockRecorder) ValidateStatusReports(ctx, reports any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
